name: diff-test
on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_DEVELOPER: "true"
        run: |
          git fetch origin master
          differs=$(git diff origin/master --name-only | fgrep .rb || true)
          if [ -z "$differs" ]; then
            echo "No changes found."
            exit 0
          fi
          echo "Changes found in: $differs"
          echo "$differs" | xargs -n 1 brew install --formula --build-from-source
