name: test
on: push

jobs:
  test:
    name: test
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: update & pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git diff --name-only origin/master | fgrep .rb | xargs -n 1 brew install --build-from-source
